packages:
  - '.'

allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  core-js-pure: true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true

overrides:
  postcss: '>=8.5.10'
